export const activities = [
  {
    id: 1,
    image: "http://funto.designing-world.com/img/bg-img/5.jpg",
    name: "NFt Logo",
    price: "0.235 ETH",
    dis: "Sales",
    time: "29 min ago",
  },
  {
    id: 2,
    image: "http://funto.designing-world.com/img/bg-img/7.jpg",
    name: "Piggy",
    price: "0.706 ETH",
    dis: "Offer",
    time: "1h ago",
  },
  {
    id: 3,
    image: "http://funto.designing-world.com/img/bg-img/8.jpg",
    name: "Car",
    price: "0.134 ETH",
    dis: "Alert",
    time: "2h ago",
  },
  {
    id: 4,
    image: "http://funto.designing-world.com/img/bg-img/13.jpg",
    name: "Monkey",
    price: "0.198 ETH",
    dis: "Sales",
    time: "3h ago",
  },
  {
    id: 5,
    image: "http://funto.designing-world.com/img/bg-img/18.jpg",
    name: "Sculpture",
    price: "0.478 ETH",
    dis: "Sales",
    time: "12 ago",
  },
  {
    id: 6,
    image: "http://funto.designing-world.com/img/bg-img/22.jpg",
    name: "Cat",
    price: "0.562 ETH",
    dis: "Discount",
    time: "17h ago",
  },
];

export const autions = [
  {
    id: "aution1",
    image:
      "https://i.seadn.io/gae/lenZ3y5d7SMv_Jfd9IKm-1nVQCIyNAtROW9vgdZRkMjvXQzP5wxz5qCPPk4niiqpVcrLVdz9htj8Q9Ga0tU0_tJgIkZhrFFjPIgr?w=500&auto=format",
    bid: "New Bid",
    profile: "http://funto.designing-world.com/img/bg-img/u2.jpg",
    stock: "3 stock availabe",
    name: "Fancy Car",
    email: "@designing_world",
    price: "0.784 Eth",
  },
  {
    id: "aution2",
    image:
      "https://i.seadn.io/gcs/files/a450a6798dbce15561f95011906e14e2.png?w=500&auto=format",
    bid: "New Bid",
    profile: "http://funto.designing-world.com/img/bg-img/u1.jpg",
    stock: "11 stock availabe",
    name: "Animal Playing with Guitar",
    email: "@creative_world",
    price: "0.861 Eth",
  },
  {
    id: "aution3",
    image: "https://i.seadn.io/gcs/files/4aa4e14b73042d482b3479de5b6c44e6.png?w=500&auto=format",
    bid: "Bid Done",
    profile: "http://funto.designing-world.com/img/bg-img/u3.jpg",
    stock: "Not availabe",
    name: "Halloween #471",
    email: "@creative_art",
    price: "0.784 Eth",
  },
  {
    id: "aution4",
    image: "https://i.seadn.io/gcs/files/93625421a671ee5ab5f4fb5d0c3ffe0f.png?w=500&auto=format",
    
    bid: "Hot Bid",
    profile: "http://funto.designing-world.com/img/bg-img/u4.jpg",
    stock: "29 stock availabe",
    name: "Vigor Dance",
    email: "@nft_fun",
    price: "0.784",
  },
  {
    id: "aution5",
    image:
      "https://i.seadn.io/gcs/files/828707b7a0298edf43a3a4561b8bd73f.png?w=500&auto=format",
    bid: "New Bid",
    profile: "http://funto.designing-world.com/img/bg-img/u2.jpg",
    stock: "3 stock availabe",
    name: "Fancy Car",
    email: "@designing_world",
    price: "0.784 Eth",
  },
  {
    id: "aution6",
    image: "https://i.seadn.io/gcs/files/130fdfe43e20a1bb44f1ebe0fc5ada6c.png?w=500&auto=format",
    bid: "New Bid",
    profile: "http://funto.designing-world.com/img/bg-img/u1.jpg",
    stock: "11 stock availabe",
    name: "Animal Playing with Guitar",
    email: "@creative_world",
    price: "0.861 Eth",
  },
  {
    id: "aution7",
    image: "https://i.seadn.io/gcs/files/2401efdcf41fd10daad9f2a3bb0d04dc.png?w=500&auto=format",
    bid: "Bid Done",
    profile: "http://funto.designing-world.com/img/bg-img/u3.jpg",
    stock: "Not availabe",
    name: "Halloween #471",
    email: "@creative_art",
    price: "0.784 Eth",
  },
  {
    id: "aution8",
    image:
      "https://i.seadn.io/gcs/files/7b6da0edb99f786f3039176e5e9f0635.png?w=500&auto=format",
    bid: "Hot Bid",
    profile: "http://funto.designing-world.com/img/bg-img/u4.jpg",
    stock: "29 stock availabe",
    name: "Vigor Dance",
    email: "@nft_fun",
    price: "0.784",
  },
  {
    id: "aution9",
    image:
      "https://i.seadn.io/gae/BdxvLseXcfl57BiuQcQYdJ64v-aI8din7WPk0Pgo3qQFhAUH-B6i-dCqqc_mCkRIzULmwzwecnohLhrcH8A9mpWIZqA7ygc52Sr81hE?w=500&auto=format",
    bid: "Hot Bid",
    profile: "http://funto.designing-world.com/img/bg-img/u4.jpg",
    stock: "29 stock availabe",
    name: "Vigor Dance",
    email: "@nft_fun",
    price: "0.784",
  },
];
