export const transactionList = [
    {
        id:1,
        image:"",
        name:"Melaine Hobs",
        quantity:"60 Items",
        type: "Buy",
        amount:"+548.00 ETH",
        date: "June 5, 08:22 PM",
    },
    {
        id:2,
        image:"",
        name:"Tewar Manforac",
        quantity:"30 Items",
        type: "Buy",
        amount:"+248.00 ETH",
        date: "June 4, 12:34 PM",
    },{
        id:3,
        image:"",
        name:"Renaixance Rising",
        quantity:"78 Items",
        type: "Buy",
        amount:"+788.00 ETH",
        date: "June 3, 02:22 PM",
    },{
        id:4,
        image:"",
        name:"Realamno Tuoipla",
        quantity:"62 Items",
        type: "Buy",
        amount:"+598.00 ETH",
        date: "June 1, 08:42 AM",
    },
]